language: python
python:
  - 3.3
  - 3.4
  - 3.5
install:
  - pip install coveralls
  - pip install coverage
  - pip install suds-jurko
script:
  coverage run --source=andreani setup.py test
after_success:
  coveralls
