language: python
python:
  - 3.3
  - 3.4
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=andreani manage.py test
after_success:
  coveralls
